# Generated by Django 6.0.7 on 2026-07-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('roll_no', models.CharField(blank=True, max_length=20)),
                ('class_name', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('added_by_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
