# Generated by Django 6.0.7 on 2026-07-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(choices=[('intent_classifier', 'Intent Classifier'), ('add_student', 'Add Student'), ('bulk_add_student', 'Bulk Add Student'), ('search_student', 'Search Student')], max_length=50, unique=True)),
                ('prompt_text', models.TextField(help_text='Use {text} or {query} as placeholder')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
