# Generated by Django 6.0.7 on 2026-07-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0002_aiaction_delete_prompttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiaction',
            name='empty_text_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
